---
- name: Load variables
  ansible.builtin.include_vars: "{{ lookup('ansible.builtin.first_found', repo_vars_params) }}"
  vars:
    repo_vars_params:
      files:
        - "{{ ansible_os_family | lower }}-{{ ansible_distribution | lower }}-{{ ansible_distribution_major_version }}.yml"
        - "{{ ansible_os_family | lower }}-{{ ansible_distribution | lower }}.yml"
        - "{{ ansible_os_family | lower }}-{{ ansible_distribution_major_version }}.yml"
        - "{{ ansible_os_family | lower }}.yml"
        - defaults.yml
      paths:
        - ../ambari_repo/vars

- name: Add the Ambari repository (yum)
  ansible.builtin.yum_repository:
    name: "ambari"
    description: "ambari Version - ambari-{{ ambari_version }}"
    baseurl: "{{ ambari_repo_url }}"
    file: 'ambari'
    state: present
    gpgcheck: "{{ ambari_repo_gpgcheck | default(false) }}"
    gpgkey: "{{ ambari_repo_url }}/RPM-GPG-KEY/RPM-GPG-KEY-Jenkins"
  when: ansible_os_family | lower == "redhat"
